# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
  displayName: 'Use python $(pythonVersion)'

- script: |
    python3 -m pip install --upgrade pip
  displayName: 'Upgrade pip'
  
- script: |
    - script: |
    python3 -m pip install wheel
    python3 -m pip install twine
    python3 -m pip install build
  displayName: 'Install build'

- task: NodeTool@0
  inputs:
    versionSpec: '12'
  displayName: 'Install npm 12'

- script: |
    python3 -m build
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Build Furo theme'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: furo/furo-release-pipeline
    pythonDownloadServiceConnections: furo-release
  displayName: 'Twine Authenticate'

- script: |
    python -m twine upload dist/*.whl -r "furo-release-pipeline" --config-file $(PYPIRC_PATH)
  displayName: 'Publish wheel to furo-release-pipeline'